// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/available-rooms": {
            "get": {
                "description": "Get available rooms",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Hotel Management"
                ],
                "summary": "Get available rooms",
                "operationId": "get-available-rooms",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"2022-12-31\"",
                        "description": "Checkin date",
                        "name": "checkin_date",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "\"2022-12-31\"",
                        "description": "Checkout date",
                        "name": "checkout_date",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Room Qty",
                        "name": "room_qty",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Room Type ID",
                        "name": "room_type_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.HotelAvailableRoomsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrResponse"
                        }
                    }
                }
            }
        },
        "/promo-rooms": {
            "post": {
                "description": "Get rooms with promo prices",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Hotel Management"
                ],
                "summary": "Get rooms with promo prices",
                "operationId": "get-promo-rooms",
                "parameters": [
                    {
                        "description": "Models of PromoRoomsRequest type",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.PromoRoomsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.PromoRoomsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.ErrResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "models.HotelAvailableRoomsResponse": {
            "type": "object",
            "properties": {
                "available_rooms": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Room"
                    }
                },
                "checkin_date": {
                    "type": "string"
                },
                "checkout_date": {
                    "type": "string"
                },
                "room_qty": {
                    "type": "integer"
                },
                "room_type_id": {
                    "type": "integer"
                },
                "total_price": {
                    "type": "integer"
                }
            }
        },
        "models.Price": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "price": {
                    "type": "integer"
                }
            }
        },
        "models.PromoRoomsRequest": {
            "type": "object",
            "properties": {
                "available_rooms": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Room"
                    }
                },
                "checkin_date": {
                    "type": "string"
                },
                "checkout_date": {
                    "type": "string"
                },
                "promo_id": {
                    "type": "integer"
                },
                "room_qty": {
                    "type": "integer"
                },
                "room_type_id": {
                    "type": "integer"
                },
                "total_price": {
                    "type": "integer"
                }
            }
        },
        "models.PromoRoomsResponse": {
            "type": "object",
            "properties": {
                "available_rooms": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Room"
                    }
                },
                "checkin_date": {
                    "type": "string"
                },
                "checkout_date": {
                    "type": "string"
                },
                "promo_id": {
                    "type": "integer"
                },
                "promo_price": {
                    "type": "integer"
                },
                "room_qty": {
                    "type": "integer"
                },
                "room_type_id": {
                    "type": "integer"
                },
                "total_price": {
                    "type": "integer"
                }
            }
        },
        "models.Room": {
            "type": "object",
            "properties": {
                "price": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Price"
                    }
                },
                "room_id": {
                    "type": "integer"
                },
                "room_number": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
